title: PM League Wiki
author: FMO
copyright: '2024'
logo: logo.png
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
execute:
  execute_notebooks: force
latex:
  latex_documents:
    targetname: book.tex
bibtex_bibfiles:
  - references.bib
repository:
  url: https://github.com/PM-League/PM-League.github.io
  path_to_book: docs
  branch: master
html:
  use_issues_button: true
  use_repository_button: true
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath
only_build_toc_files: true

# sphinx:
#   config:
#     html_theme: sphinx_book_theme
